---
- name: "server"
  conn:
    - redis:
        host: '10.0.0.88'
        port: 6379
        passwd: '***********'

    - mysql:
        host: '10.0.0.88'
        port: 3306
        user: 'root'
        passwd: '***********'
        dbname: 'test'

  log:
    # level:  1-5, debug-critical
    # status: 'open' or 'close' | True or False | 1 or 0 | 'yes' or 'no' | 'y' or 'n'
    - optional: ['debug', 'info', 'warning', 'error', 'critical']
    - level: 2
    - status: y

...
